version: '3'

services:
  rinha-api-01: &api
    hostname: rinha-api-01
    container_name: rinha-api-01
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"

  rinha-api-02:
    <<: *api
    hostname: rinha-api-02
    container_name: rinha-api-02
    ports:
      - "3002:3000"
    depends_on:
      - db

  db:
    image: postgres:16.1
    container_name: rinha-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=rinha
      - POSTGRES_PASSWORD=R1nh@Cr3b1t0!
      - POSTGRES_DB=crebito
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096 -c synchronous_commit=0
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "70MB"

  nginx:
    image: nginx:latest
    container_name: nginx-rinha-2024

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - rinha-api-01
      - rinha-api-02

    ports:
      - "9999:9999"

    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "15MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
